"""
driver_gen — generate a Kyxen keyboard driver from profiler data.

Input:
  - model_name: str          e.g. "G512"
  - product_id: int          e.g. 0xC33F
  - gkey_count: int
  - key_ids: dict[int, str]  led_id (int) → key_name (str), from probe
  - layout: list of (name, x, y, w, h) from the layout editor

Output: Python source code string ready to save as a .py file.

Generated drivers use absolute imports so they can be loaded dynamically
from ~/.config/kyxen/drivers/ without being part of the kyxen_keys package.
"""
from __future__ import annotations


def _safe_ident(model_name: str) -> str:
    """Turn 'G512 RGB' into 'G512RGB' for use in class/file names."""
    return ''.join(c for c in model_name if c.isalnum() or c == '_')


def suggested_filename(model_name: str) -> str:
    return f'logitech_{_safe_ident(model_name).lower()}.py'


def generate(
    model_name: str,
    product_id: int,
    gkey_count: int,
    key_ids: dict[int, str],       # led_id → key_name
    layout: list[tuple[str, float, float, float, float]],
) -> str:
    """Return Python source for a new keyboard driver."""

    ident      = _safe_ident(model_name)
    class_name = f'Logitech{ident}'

    # KEY_IDS section — sort by LED address
    key_ids_items = sorted(key_ids.items())
    key_ids_lines = [f'    {name!r}: 0x{led_id:02X},' for led_id, name in key_ids_items]

    # LAYOUT section
    layout_lines = [f'    KeyRect({name!r}, {x}, {y}, {w}, {h}),' for name, x, y, w, h in layout]

    key_ids_block = '\n'.join(key_ids_lines) if key_ids_lines else '    # (empty — run the probe)'
    layout_block  = '\n'.join(layout_lines)  if layout_lines  else '    # (empty — fill in key positions)'

    gkey_note = ''
    if gkey_count > 0:
        gkey_note = '\n    # TODO: add evdev keycodes emitted by the G-key interface.\n    # GKEY_SUPPRESS_CODES: frozenset[int] = frozenset({...})'

    return f'''\
# Generated by Kyxen Profiler
# Install: drop this file into  ~/.config/kyxen/drivers/
# Contribute: open a PR at https://github.com/quinn-stack/kyxen
#
# Review KEY_IDS and LAYOUT before use — the probe may have misidentified
# modifier keys (L/R Shift etc.) or assigned wrong names to special keys.
from __future__ import annotations
from kyxen_keys.keyboards.base import LogitechKeyboard, DevicePaths
from kyxen_keys.keyboard_layout import KeyRect


# LED address map: key_name → HID++ LED id.
# Built by kyxen-profiler; verify with tools/probe_lighting.py.
KEY_IDS: dict[str, int] = {{
{key_ids_block}
}}

# Physical key layout — positions in "key units" (1u ≈ standard key width).
# X=0, Y=0 = top-left corner of the keyboard.
LAYOUT: list[KeyRect] = [
{layout_block}
]


class {class_name}(LogitechKeyboard):
    PRODUCT_IDS = [0x{product_id:04X}]
    MODEL_NAME  = 'Logitech {model_name}'
    GKEY_COUNT  = {gkey_count}{gkey_note}

    def get_key_ids(self) -> dict[str, int]:
        return KEY_IDS

    @classmethod
    def detect(cls) -> \'{class_name} | None\':
        from kyxen_keys.keyboards.detect import find_evdev, find_hidraw, find_hidraw_for_evdev
        evdev_path = find_evdev(cls.VENDOR_ID, cls.PRODUCT_IDS, cls._is_gkey_interface)
        if evdev_path is None:
            return None
        gkeys_hidraw = find_hidraw_for_evdev(evdev_path) or \'\'
        hidraw_path  = find_hidraw(cls.VENDOR_ID, cls.PRODUCT_IDS, exclude=gkeys_hidraw) or gkeys_hidraw
        return cls(DevicePaths(evdev=evdev_path, hidraw=hidraw_path, hidraw_gkeys=gkeys_hidraw))

    def apply_lighting(self, mode: str, colour: str, active_mkey: int | None = None) -> None:
        pass
'''
